### PR TITLE
Fixes #7 Added method that displays frequency of all letters of file,…

### LINKED ISSUE #7: [Student A] Generate report about count of every letter in the file
Check instructions from the doc

### PR DESCRIPTION
**Pull request by javorske**
… another method that checks if file was downloaded/exists and changed return types of old methods

### CODE REVIEW

**Review by python27 — APPROVED** [review]
Very good!

**Review by Zeever00 — CHANGES_REQUESTED** [review]
If we push this, we are 1 branch reversed. Can u push it again with updated repo?

**Review by python27 — CHANGES_REQUESTED** [review]
Can you correct it javorske?

**Review by Zeever00 — APPROVED** [review]
It good now :D

**Review by python27 — APPROVED** [review]
ok

**Pull request merged**
